import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * Low-quality image placeholders, generated by scripts/mirror-media.mjs and
 * shipped inside .media-cache alongside the images themselves.
 *
 * Keyed by the normalised source URL — the same string /api/media hashes — so
 * lookups must normalise through resolveSourceAssetUrl first.
 *
 * Read synchronously and memoised: the HTML sanitiser that consumes this is
 * synchronous with call sites throughout lib/content/transform.ts, and
 * threading a promise through all of them buys nothing for a file that is read
 * once per process. Missing or malformed manifests degrade to no placeholder.
 */
let manifest: Record<string, string> | null = null;

function loadManifest(): Record<string, string> {
  if (manifest) {
    return manifest;
  }

  const dir = process.env.MEDIA_CACHE_DIR ?? join(process.cwd(), '.media-cache');

  try {
    const parsed: unknown = JSON.parse(readFileSync(/*turbopackIgnore: true*/ join(dir, 'lqip.json'), 'utf-8'));
    manifest = parsed && typeof parsed === 'object' ? (parsed as Record<string, string>) : {};
  } catch {
    manifest = {};
  }

  return manifest;
}

export function getLqipDataUri(sourceUrl: string): string | undefined {
  const value = loadManifest()[sourceUrl];
  return typeof value === 'string' && value.startsWith('data:image/') ? value : undefined;
}

/** Test seam — the manifest is otherwise cached for the life of the process. */
export function resetLqipManifestForTests(): void {
  manifest = null;
}
